
shinhan:
  apiKey: 2023_Shinhan_SSAFY_Hackathon

spring:
  datasource:
    url: jdbc:h2:mem:ssoc
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    defer-datasource-initialization: true
    generate-ddl: true

    hibernate:
      ddl-auto: create-drop

    open-in-view: false

    properties:
      hibernate:
        format_sql: true
        show_sql: true
        jdbc:
          batch_size: 100
        default_batch_fetch_size: 100

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: donggeun3484@gmail.com
    password: tbplnbqivtwteeki
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK

  expired-min:
    access: 60   # 액세스 토큰 만료제한시간 60분 (1시간)
    refresh: 10080  # 리프레쉬 토큰 만료제한시간 10080분 (7일)
